timestamps {

  node('my-host') {
  // Start Stages
    stage('Clone') {
      checkout([$class: 'GitSCM',
                  branches: [[name: 'dev']],
                  doGenerateSubmoduleConfigurations: false,
                  extensions: [],
                  submoduleCfg: [],
                  userRemoteConfigs: [[credentialsId: 'github', url: 'https://github.com/arunodhayamsam/node-app.git']]
                ])    
    }  
    stage('Dockebuild and Push') {
        withEnv(["DISABLE_AUTH=new"]) {
         echo "hello ${env.DISABLE_AUTH}"    
          sh 'rm -f ~/.dockercfg ~/.docker/config.json || true'

  // configure registry
         docker.withRegistry('https://507180652719.dkr.ecr.us-east-1.amazonaws.com/node-app', 'ecr:us-east-1:new-ecr') {

    // build image
         def customImage = docker.build("node-app:${env.BUILD_ID}")

    // push image
         def taskdef = customImage.push()
         echo "hello ${env.DISABLE_AUTH}"
         } 
      }
    }
    
    stage('Update ECS Service') {
         // echo ${DOCKET_IMAGE}
         sh '''#!/bin/bash
            sed -i "s/IMG_TAG/${BUILD_NUMBER}/g" task-definition.json
            cat task-definition.json
            '''
     
   
   }
  }  
}

